<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Launched the Browser]]>
    </line>
    <line>
      <![CDATA[Logged in to the app]]>
    </line>
    <line>
      <![CDATA[Logged out from the app]]>
    </line>
    <line>
      <![CDATA[Logged in to the app]]>
    </line>
    <line>
      <![CDATA[Logged out from the app]]>
    </line>
    <line>
      <![CDATA[Launched the Browser]]>
    </line>
    <line>
      <![CDATA[Logged in to the app]]>
    </line>
    <line>
      <![CDATA[Logged out from the app]]>
    </line>
  </reporter-output>
  <suite started-at="2022-12-20T19:33:31 IST" name="Suite" finished-at="2022-12-20T19:34:08 IST" duration-ms="37022">
    <groups>
    </groups>
    <test started-at="2022-12-20T19:33:31 IST" name="Test" finished-at="2022-12-20T19:34:08 IST" duration-ms="37022">
      <class name="ContactsDemoblaze">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:ContactsDemoblaze@550dbc7a]" started-at="2022-12-20T19:33:31 IST" name="beforeSuite" finished-at="2022-12-20T19:33:39 IST" duration-ms="7180" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Launched the Browser]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="loginApp()[pri:0, instance:ContactsDemoblaze@550dbc7a]" started-at="2022-12-20T19:33:40 IST" name="loginApp" finished-at="2022-12-20T19:33:43 IST" duration-ms="3489" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged in to the app]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginApp -->
        <test-method signature="contactDemoblazeTest(java.lang.String,java.lang.String)[pri:0, instance:ContactsDemoblaze@550dbc7a]" started-at="2022-12-20T19:33:43 IST" name="contactDemoblazeTest" data-provider="contactTest" finished-at="2022-12-20T19:33:45 IST" duration-ms="1437" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[san123@gamil.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[santosh]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at ContactsDemoblaze.contactDemoblazeTest(ContactsDemoblaze.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactDemoblazeTest -->
        <test-method is-config="true" signature="logutApp()[pri:0, instance:ContactsDemoblaze@550dbc7a]" started-at="2022-12-20T19:33:45 IST" name="logutApp" finished-at="2022-12-20T19:33:46 IST" duration-ms="1417" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged out from the app]]>
            </line>
          </reporter-output>
        </test-method> <!-- logutApp -->
        <test-method is-config="true" signature="loginApp()[pri:0, instance:ContactsDemoblaze@550dbc7a]" started-at="2022-12-20T19:33:46 IST" name="loginApp" finished-at="2022-12-20T19:33:51 IST" duration-ms="4927" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged in to the app]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginApp -->
        <test-method signature="contactDemoblazeTest(java.lang.String,java.lang.String)[pri:0, instance:ContactsDemoblaze@550dbc7a]" started-at="2022-12-20T19:33:51 IST" name="contactDemoblazeTest" data-provider="contactTest" finished-at="2022-12-20T19:33:52 IST" duration-ms="1424" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[prav123@gamil.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hardik]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at ContactsDemoblaze.contactDemoblazeTest(ContactsDemoblaze.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactDemoblazeTest -->
        <test-method is-config="true" signature="logutApp()[pri:0, instance:ContactsDemoblaze@550dbc7a]" started-at="2022-12-20T19:33:52 IST" name="logutApp" finished-at="2022-12-20T19:33:53 IST" duration-ms="1114" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged out from the app]]>
            </line>
          </reporter-output>
        </test-method> <!-- logutApp -->
        <test-method is-config="true" signature="afterSuit()[pri:0, instance:ContactsDemoblaze@550dbc7a]" started-at="2022-12-20T19:33:53 IST" name="afterSuit" finished-at="2022-12-20T19:33:54 IST" duration-ms="874" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuit -->
      </class> <!-- ContactsDemoblaze -->
      <class name="AddToCart">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:AddToCart@12aba8be]" started-at="2022-12-20T19:33:54 IST" name="beforeSuite" finished-at="2022-12-20T19:33:58 IST" duration-ms="3396" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Launched the Browser]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="loginApp()[pri:0, instance:AddToCart@12aba8be]" started-at="2022-12-20T19:33:58 IST" name="loginApp" finished-at="2022-12-20T19:34:02 IST" duration-ms="3794" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged in to the app]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginApp -->
        <test-method signature="addCart()[pri:0, instance:AddToCart@12aba8be]" started-at="2022-12-20T19:34:02 IST" name="addCart" finished-at="2022-12-20T19:34:05 IST" duration-ms="3854" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at AddToCart.addCart(AddToCart.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCart -->
        <test-method is-config="true" signature="logutApp()[pri:0, instance:AddToCart@12aba8be]" started-at="2022-12-20T19:34:05 IST" name="logutApp" finished-at="2022-12-20T19:34:07 IST" duration-ms="1831" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged out from the app]]>
            </line>
          </reporter-output>
        </test-method> <!-- logutApp -->
        <test-method is-config="true" signature="afterSuit()[pri:0, instance:AddToCart@12aba8be]" started-at="2022-12-20T19:34:07 IST" name="afterSuit" finished-at="2022-12-20T19:34:08 IST" duration-ms="1148" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuit -->
      </class> <!-- AddToCart -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
